// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		double bigger = 0;
		double smaller = 0;

	    for (int i = 0; i < N; i++) {
			double random = Math.random();

			if (random > 0.5) {
				 bigger++;
			} else {
				smaller++;
			}
		}

		System.out.println("> 0.5: " + bigger);
		System.out.println("<= 0.5: " + smaller);

		if (smaller > 0) {
			double ratio = (double) bigger / smaller;
			System.out.println(ratio);
		}
	}
}
